name: E2E Security Scans

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=mycasestudy -Dsonar.projectKey=mycasestudy_gitcase

  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    needs: sonarqube
    # Always run Snyk scan, even if SonarQube fails
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  owasp_zap:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: snyk
    # Always run OWASP ZAP scan, even if Snyk fails
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://www.zaproxy.org'